language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_HOST
    - secure: "UtOJrmzC+y4gCg2j4shJAC8lqDPOiYQl6CBmEg3iiA30wT2x2DArUBeO38OS4lvRUGdn61aH07fNyfOUDHTWw7R/Zo0EgZRkBJMyB5J5/xQBLJXg5PfFxC4qzQuULo3ei8xdSKXyV7V/zhxSDzLIzWrAMxLSS7TZHt8N1Yb+YmnfLeOL5qvM/bN4kpF/mmSFW+n1q/sR36RvrwG9Vv6CGuuuGGYbieV0X+XPAIdmKB225LI1ta6tY6eJcGgYyOrlhNIhSZVt328WNgIraGkNxotLz/f4R53ouEjl8QR0bw4TTOHhMr1yIxgWtWxoH835ERKr+GGyuJBO3HWL1PVtVwwpGMdBXj6zwHW8TaeeahBxOk4J4mpOUcehrM/7KcRf50qDlvoFkbrT6u6T12VoROAhyHnpf2WS9T3eDD3I39CzSGyd3TTMaoKb8B/k1/5X6pKfOKK3VMWZi2Xa3pXCRW5eQ0HQH+sGS07ILD22jkorlZv8grNjqGUAcwRYc+bKhe7lwgMPX8sg6PEJyslgcB7Jz6WYYs4zps1DwYEj26OpkF5PepH0VUxE7A+COHasFylnFBBGxGCA3PtIL4IXRW1tZtGjwCmWKAjku4ttX99V+OlDtQnkiMUpnntPTW4tro+K3KmWqpTh3tlMLuPJmgVj3cpFDv0zgdc5QqPxdGc="

branches:
  except:
    - /^(?i:continuous)$/

script:
  - wget -c https://raw.githubusercontent.com/lirios/infra-travis/master/run
  - bash run ./.travis/build.sh

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
